预演

开发-you:make distcheck webu:ubuntu-blue-you:you:
在预演:
在
- -名称：配置: 名字
让 distcheck you-cpp. yml you

切换
控制+换挡+m使用:

建筑

空文件
切换
突耳
按键移动焦点。或者，使用
请将下面的文本准确无误地翻译成
然后
突耳
移动到页面上的下一个交互元素。
使用[[控制+空间]]触发自动完成。
使用
